
[eco-rubygems]
image = "wschenk/eco-rubygems"
service = "eco-rubygems"

[lock-gemfile]
image = "wschenk/lock-gemfile"
service = "lock-gemfile"

[lock-packagelock]
image = "wschenk/lock-packagelock"
service = "lock-packagelock"

[lock-yarnlock]
image = "wschenk/lock-yarnlock"
service = "lock-yarnlock"

[projects]
database = "postgres-postgresql"
image = "wschenk/projects"
schema = "projects"
service = "projects"

[repositories]
database = "postgres-postgresql"
image = "wschenk/repositories"
schema = "repositories"
service = "repositories"

[ruby-echo]
image = "wschenk/ruby-echo"
no-tls = true
service = "ruby-echo"

[ruby-send]
image = "wschenk/ruby-send"
no-tls = true
service = "ruby-send"

[vcs-git]
image = "wschenk/vcs-git"
service = "vcs-git"
