
[databases.postgres-postgresql]
database_url = ["postgres-postgresql-repositories"]

[global]
context = "do-nyc1-gratitude"
domain = "gitgratitude.com"
image_prefix = "wschenk/"

[projects]
configmap = ["postgres-postgresql-projects","gratitude-config"]
database = "postgres-postgresql"
image = "wschenk/projects"
service = "projects"

[repositories]
binding = true
configmap = ["postgres-postgresql-repositories","gratitude-config"]
database = "postgres-postgresql"
events = ["git.done"]
image = "wschenk/repositories"
service = "repositories"

[vcs-git]
binding = true
configmap = ["gratitude-config","s3-access"]
events = ["git.process"]
image = "wschenk/vcs-git"
service = "vcs-git"
