---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: postgres-backup
spec:
  schedule: "@daily"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: backup
            image: wschenk/backup
            imagePullPolicy: Always
            envFrom:
            - configMapRef:
                name: s3-access
            env:
            - name: PROJECTS_DATABASE_URL
              valueFrom:
                configMapKeyRef:
                  name: postgres-postgresql-projects
                  key: DATABASE_URL
            - name: REPOSITORIES_DATABASE_URL
              valueFrom:
                configMapKeyRef:
                  name: postgres-postgresql-repositories
                  key: DATABASE_URL
            - name: WATCHER_DATABASE_URL
              valueFrom:
                configMapKeyRef:
                  name: postgres-postgresql-watcher
                  key: DATABASE_URL
          restartPolicy: Never
